function net = rnntrain(XTrain,YTrain)
wd=6;
%% V.网络构建
layers=get_lstm_net(wd);

deepNetworkDesigner

options=trainingOptions('adam',...
    'MaxEpochs',1000,...
    'GradientThreshold',1,...
    'InitialLearnRate',0.005, ...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropPeriod',125,...
    'LearnRateDropFactor',0.2,...
    'Verbose',0,...
    'Plots','training-progress');

%% VI.训练
net=trainNetwork(XTrain,YTrain,layers,options);
end